service: aws-node # NOTE: update this with your service name
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
 name: aws
 profile: f5
 stage: dev
 runtime: nodejs20.x

functions:
  lambdafx:
    handler: index.handler
    events:
      - http:
          path: mi-funcion
          method: get
  ping:
    handler: index.ping
    events:
      - http:
          path: ping
          method: get
  test:
    handler: index.test
    events:
      - http:
          path: test
          method: get
  mark:
    handler: index.mark
    events:
      - http:
          path: mark
          method: post